import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "./Providers";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import ClientSWRConfig from "./ClientSWRConfig";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata: Metadata = {
  title: "Butter's Dream",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} w-full min-h-screen bg-background text-foreground bg-[url('/cloudes.png')] bg-cover animate-moveBackground `}
      >
        <Providers>
          <div className="max-w-md w-full mx-auto p-4 pb-16">
            <ClientSWRConfig>
              <Header />
              {children}
              <NavBar />
            </ClientSWRConfig>
          </div>
        </Providers>
      </body>
    </html>
  );
  //2 4 3 1
}
